apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod
  name: my-pod
  namespace: mudasir
spec:
  containers:
    - image: task-management-app:v1
      imagePullPolicy: IfNotPresent
      name: my-pod
      resources: {}
      command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
