services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: task-manager-backend
    container_name: task-manager-backend
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: task-manager-ui
    container_name: task-manager-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      API_BASE_URL: http://api:8000
      LLM_BASE_URL: http://host.docker.internal:11434/v1
    depends_on:
      - api
