kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-management-deployer #This is the name of guy who deploy this
  namespace: taskmanagement
rules:
  - apiGroups: ["apps"]
    resources: ["deployment", "replicasets"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list"]
