version: "3.9"

services:
  task-manager-app:
    build:
      context: ./task-manager-app
      dockerfile: Dockerfile.multistage
    image: task-manager-image
    container_name: task-manager-app
    ports:
      - "8001:8000"

  task-viewer-app:
    build:
      context: ./task-viewer-app
      dockerfile: Dockerfile.multistage
    image: task-viewer-image
    container_name: task-viewer-app
    ports:
      - "8002:8000"
    depends_on:
      - task-manager-app
    environment:
      TASK_MANAGER_URL: http://task-manager-app:8000
