FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv && uv pip install --system --no-cache -r pyproject.toml

COPY . .

EXPOSE 8000

LABEL NAME="My TaskManagement App" \
      VERSION="1.0.0" \
      DESCRIPTION="A simple Task Management application running in Docker" \
      AUTHOR="Mudasir Irshad"


CMD [ "uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]